# Generated by Django 3.2.12 on 2022-02-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pics')),
                ('detail', models.TextField()),
            ],
        ),
    ]
